#!/bin/bash
# Auto-configuration script for Monero SuperPay Umbrel App
# Reads Monero node credentials from Umbrel's monero app and configures this app.
# Run this before `docker compose up` on first install, or when Monero credentials change.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUR_ENV_FILE="${SCRIPT_DIR}/.env"
UMBREL_MONERO_DIR="${HOME}/umbrel/app-data/monero"
UMBREL_MONERO_ENV="${UMBREL_MONERO_DIR}/.env"

echo "======================================"
echo "  Monero SuperPay - Auto-Configuration"
echo "======================================"
echo ""

# --- Detect Monero node IP ---
get_monerod_ip() {
    # Try docker inspect first
    local ip=$(docker inspect monero_monerod_1 --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 2>/dev/null || echo "")
    if [ -z "$ip" ]; then
        # Fallback: check umbrel_main_network
        ip=$(docker network inspect umbrel_main_network 2>/dev/null | grep -A5 "monero_monerod_1" | grep "IPv4Address" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -1 || echo "")
    fi
    echo "$ip"
}

# --- Read RPC credentials from Umbrel Monero app ---
get_monero_credentials() {
    if [ -f "$UMBREL_MONERO_ENV" ]; then
        source "$UMBREL_MONERO_ENV"
        echo "${APP_MONERO_RPC_USER:-monero}:${APP_MONERO_RPC_PASS:-monero}"
    else
        echo "monero:monero"
    fi
}

# --- Check Monero app is installed ---
if [ ! -d "$UMBREL_MONERO_DIR" ]; then
    echo "WARNING: Umbrel Monero app not found at $UMBREL_MONERO_DIR"
    echo "         Please install the Monero app from Umbrel App Store first."
    echo "         Continuing with defaults (may not connect to node)..."
    echo ""
fi

# --- Detect Monero node ---
echo "Detecting Monero node..."
MONEROD_IP=$(get_monerod_ip)
if [ -z "$MONEROD_IP" ]; then
    echo "  Could not auto-detect Monero node IP. Using container name fallback."
    MONEROD_IP="monero_monerod_1"
else
    echo "  Found Monero node at: $MONEROD_IP"
fi

# --- Read RPC credentials ---
echo "Reading Monero RPC credentials..."
CREDS=$(get_monero_credentials)
RPC_USER=$(echo "$CREDS" | cut -d: -f1)
RPC_PASS=$(echo "$CREDS" | cut -d: -f2-)

if [ "$RPC_USER" != "monero" ] || [ "$RPC_PASS" != "monero" ]; then
    echo "  Found custom RPC credentials from Monero app"
else
    echo "  Using default credentials (monero:monero)"
fi

# --- Generate app secret if not set ---
APP_SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | xxd -p | tr -d '\n')

# --- Write .env ---
echo ""
echo "Writing configuration to $OUR_ENV_FILE..."

cat > "$OUR_ENV_FILE" << EOF
# Auto-generated by init-config.sh — $(date)
# Re-run this script if your Monero node credentials change.

# Monero Node Connection (from Umbrel's Monero app)
APP_MONERO_NODE_IP=${MONEROD_IP}
APP_MONERO_RPC_PORT=18081
APP_MONERO_RPC_USER=${RPC_USER}
APP_MONERO_RPC_PASS=${RPC_PASS}

# App Configuration
APP_MONERO_SUPERPAY_PORT=3033
APP_MONERO_SUPERPAY_FIAT=USD
APP_MONERO_SUPERPAY_BUSINESS_NAME=Monero SuperPay
APP_SEED=${APP_SECRET}

# Network
SUBNET_ID=22
APP_DATA_DIR=./data
DEVICE_DOMAIN_NAME=umbrel.local
EOF

echo "  Done!"
echo ""
echo "======================================"
echo "  Ready! Run:  docker compose up -d"
echo "======================================"
